modLoader="javafml"
loaderVersion="[1,)"
license="${mod_license}"
issueTrackerURL="https://github.com/ponuing/ChestTracker/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/ponuing/ChestTracker"
logoFile="assets/chesttracker/icon.png"
authors="JackFred; ponuing; unofficial NeoForge port"
description='''Client-side item storage and searching for Minecraft 26.1.2. Unofficial NeoForge port.'''

[[mixins]]
config="chesttracker.mixins.json"

[[mixins]]
config="jackfredlib-gps.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="yet_another_config_lib_v3"
type="required"
versionRange="[3.9.1,)"
ordering="AFTER"
side="CLIENT"
